[package]
name = "ppcalc_metric"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7.0"
csv = "1.2.0"
serde = { version = "1", features = ["derive"] }
time = { version = "0.3.20", features = ["macros", "serde-human-readable"] }
fxhash = "0.2"
serde_json = "1.0.96"